# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electroshop', '0002_siteprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
