# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electroshop', '0003_auto_20160225_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SiteProfile',
        ),
    ]
