# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electroshop', '0004_auto_20160225_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
    ]
