# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electroshop', '0005_remove_userprofile_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='delivery',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='electroshop.UserProfile'),
        ),
    ]
