# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('electroshop', '0006_auto_20160307_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='electroshop.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
