# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 01:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('electroshop', '0007_auto_20160307_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='delivery_address',
            field=models.CharField(default=datetime.datetime(2016, 3, 7, 1, 42, 3, 865354, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=datetime.datetime(2016, 3, 7, 1, 42, 12, 215860, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
